---
abstract: 'An LWP user agent that can display a progress bar'
author:
  - 'Marcel GrE<uuml>nauer, C<< <marcel@cpan.org> >>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::Differences: 0
  Test::More: 0.70
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.91'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: LWP-UserAgent-ProgressBar
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  LWP::UserAgent: 0
  Term::ProgressBar: 0
  perl: 5.6.0
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=LWP-UserAgent-ProgressBar
  homepage: http://search.cpan.org/dist/LWP-UserAgent-ProgressBar/
  license: http://dev.perl.org/licenses/
  repository: git://github.com/hanekomu/lwp-useragent-progressbar.git
version: 0.04
