---
abstract: 'An LWP user agent that can display a progress bar'
author:
  - 'Marcel Gruenauer <marcel@cpan.org>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.11
generated_by: 'Dist::Zilla version 1.100711'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: LWP-UserAgent-ProgressBar
provides:
  LWP::UserAgent::ProgressBar:
    file: lib/LWP/UserAgent/ProgressBar.pm
    version: 1.100810
requires:
  Carp: 0
  Cwd: 0
  English: 0
  File::Find: 0
  File::Spec: 0
  File::Temp: 0
  LWP::UserAgent: 0
  Scalar::Util: 0
  Term::ProgressBar: 0
  Test::Differences: 0
  Test::More: 0.88
  perl: 5.008
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=LWP-UserAgent-ProgressBar
  homepage: http://search.cpan.org/dist/LWP-UserAgent-ProgressBar/
  repository: http://github.com/hanekomu/LWP-UserAgent-ProgressBar
version: 1.100810
